"""Minimal Markdown renderer for GitHub release notes, using ``tk.Text`` tags.

Renders only the subset of Markdown that actually shows up in this project's
own release bodies. Those bodies are 100% generated by git-cliff from
``cliff.toml``'s ``body`` template (see ``RELEASING.md`` -- there is no
hand-editing step), and reading that template plus two real releases
(``gh release view 1.0.0``/``1.0.1 --json body``) pins the shapes down
exactly:

- ``### {{ group }}`` section headings -- always level 3, but ``#``/``##``
  are supported too since nothing stops a future template change or a
  differently-configured fork from emitting them.
- ``- {{ commit }}`` bullets, one per commit.
- ``**BREAKING** `` prefixing a bullet, from ``{% if commit.breaking %}``.
- `` `identifier` `` inline code spans -- not from the template itself, but
  a real and recurring feature of this repo's *commit message* style (e.g.
  "publish `opened` last", "drop its dead `name` key" -- see
  ``git log --oneline --all | grep '`'``), which git-cliff copies verbatim
  into the message text.
- `` by @{{ commit.remote.username }} in #{{ commit.remote.pr_number }}``
  appended to a line -- explicitly called out in ``CLAUDE.md`` §8.

Markdown links (``[text](url)``) and bare ``https://`` URLs are handled too,
defensively: nothing in the current template emits either, but a release
body is attacker-influenced in principle (any repo
``CASESORTER_UPDATE_REPO`` points at -- see ``sorter/update/updater.py``), and a
hand-edited or differently-templated body could carry them. Rather than
special-case "did the shape change", the same tokenizer just also
recognises them.

Everything here is a line-oriented, single-pass regex tokenizer -- no
recursive grammar, no ``eval``, nothing that executes. An input that doesn't
look like any of the above falls through as plain text; the entry point
never raises, and always leaves the widget showing *something* readable
rather than blank or broken.
"""

from __future__ import annotations

import re
import tkinter as tk
import webbrowser
from urllib.parse import quote

from .theme import PALETTE

# A real release body is a few KB. The update endpoint is attacker-influenced
# in principle, so cap how much we'll ever try to lay out -- an enormous body
# must degrade to "truncated", not wedge the UI laying out megabytes of text.
_MAX_SOURCE_CHARS = 100_000
_MAX_LINES = 4_000

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
_BULLET_RE = re.compile(r"^[-*]\s+(.*)$")

# Inline tokens, tried left-to-right at each position via alternation (first
# match wins, like every regex engine's alternation). Every branch is linear
# in the input -- no quantifier nested inside another over the same class --
# so this can't exhibit the catastrophic-backtracking blowup a pattern like
# `(a+)+` would on adversarial input.
_INLINE_RE = re.compile(
    r"(?P<link>\[(?P<link_text>[^\]\n]+)\]\((?P<link_url>https?://[^\s()]+)\))"
    r"|(?P<bold>\*\*(?P<bold_text>[^\n]+?)\*\*)"
    r"|(?P<code>`(?P<code_text>[^`\n]+)`)"
    r"|(?P<user>(?<![\w/])@(?P<user_name>[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?(?:\[bot])?))"
    r"|(?P<pr>(?<![\w#])#(?P<pr_num>\d+))"
    r"|(?P<url>https?://[^\s()<>\[\]]+)"
)


def _open_url(url: str) -> None:
    """Open a URL in the default browser -- and nothing but http(s).

    The release body this URL came from is attacker-influenced in principle,
    so a scheme check happens here, right before the only place that could
    act on it, rather than trusting the regex that found it. Blocks
    `javascript:`, `file:`, custom protocol handlers, etc.
    """
    if url.lower().startswith(("http://", "https://")):
        try:
            webbrowser.open(url)
        except Exception:
            pass  # best-effort, same spirit as sysutil.open_path


def _user_url(name: str) -> str:
    # GitHub bot accounts (`renovate[bot]`, `dependabot[bot]`, ...) don't have
    # a normal profile -- their page lives under /apps/<name-without-suffix>.
    if name.endswith("[bot]"):
        return f"https://github.com/apps/{quote(name[: -len('[bot]')])}"
    return f"https://github.com/{quote(name)}"


def _pr_url(repo: str, number: str) -> str:
    # GitHub redirects /issues/<n> to /pull/<n> when it's actually a PR (and
    # vice versa), so there's no need to know which one #N is.
    return f"https://github.com/{repo}/issues/{number}"


def _configure_tags(widget: tk.Text, fonts: dict[str, tuple]) -> None:
    """(Re)configure the paragraph-level tags from the live palette/fonts.

    Called on every render, not once at widget-build time: ``PALETTE`` is
    mutated in place on a theme switch (theme.py's rule -- see CLAUDE.md
    §5), and nothing walks a ``tk.Text``'s *tags* the way
    ``theme.retheme_widgets`` walks ordinary widget color options (it only
    ever inspects ``cget`` on the widget itself). Re-deriving colors here
    from the current ``PALETTE`` each time ``render_release_notes`` runs
    keeps the notes pane correct across a theme switch without adding a
    second, tag-aware retheming mechanism for what is (so far) the only
    ``tk.Text`` in the app with content-driven tags.
    """
    widget.tag_configure("body", font=fonts["body"], foreground=PALETTE["text"], spacing3=4)
    widget.tag_configure("h1", font=fonts["title"], foreground=PALETTE["text_highlight"], spacing1=6, spacing3=6)
    widget.tag_configure("h2", font=fonts["header"], foreground=PALETTE["text_highlight"], spacing1=6, spacing3=4)
    # h3 is what the app's own release notes actually use (cliff.toml only
    # ever emits `###`). Accent rather than the highlight color: it needs to
    # stand out from body text without spending one of the app's few
    # reserved hues (CLAUDE.md §5, "Hue is meaning") on a release-notes pane.
    widget.tag_configure("h3", font=fonts["header"], foreground=PALETTE["accent"], spacing1=6, spacing3=4)
    # Hanging indent: lmargin1 places the bullet glyph, lmargin2 is where a
    # wrapped continuation line lines back up under the text (not the glyph).
    widget.tag_configure("bullet", font=fonts["body"], foreground=PALETTE["text"], lmargin1=18, lmargin2=32, spacing3=2)
    # Configured after the paragraph tags above so they win the priority tie
    # when combined with one of them (Tk gives a later-created tag higher
    # display priority) -- e.g. `**BREAKING**` inside a bullet must render in
    # the bold font, not the bullet tag's plain one.
    widget.tag_configure("bold", font=fonts["bold"])
    widget.tag_configure("code", font=fonts["mono"], background=PALETTE["bg_card"], foreground=PALETTE["text"])


def _insert_link(widget: tk.Text, label: str, url: str, base_tags: tuple[str, ...], registry: list[str]) -> None:
    """Insert `label` as a clickable span opening `url`, and track its tag.

    Each link gets its own uniquely-named tag (rather than one shared "link"
    tag) because the click handler needs to know *which* URL this particular
    span points at; `registry` collects the names so the caller can
    `tag_delete` them before the next render instead of leaking a growing
    set of dead tag definitions across repeated re-renders (e.g. clicking
    through several releases in the version picker).
    """
    tag = f"md_link_{len(registry)}"
    registry.append(tag)
    widget.tag_configure(tag, foreground=PALETTE["accent"], underline=True)
    widget.tag_bind(tag, "<Button-1>", lambda _e, u=url: _open_url(u))
    widget.tag_bind(tag, "<Enter>", lambda _e: widget.config(cursor="hand2"))
    widget.tag_bind(tag, "<Leave>", lambda _e: widget.config(cursor=""))
    widget.insert(tk.END, label, (*base_tags, tag))


def _emit_inline(widget: tk.Text, text: str, base_tags: tuple[str, ...], repo: str, registry: list[str]) -> None:
    """Insert one line's worth of text, applying inline tokens as it goes."""
    pos = 0
    for m in _INLINE_RE.finditer(text):
        if m.start() > pos:
            widget.insert(tk.END, text[pos : m.start()], base_tags)
        if m.group("link"):
            _insert_link(widget, m.group("link_text"), m.group("link_url"), base_tags, registry)
        elif m.group("bold"):
            widget.insert(tk.END, m.group("bold_text"), (*base_tags, "bold"))
        elif m.group("code"):
            widget.insert(tk.END, m.group("code_text"), (*base_tags, "code"))
        elif m.group("user"):
            _insert_link(widget, m.group("user"), _user_url(m.group("user_name")), base_tags, registry)
        elif m.group("pr"):
            _insert_link(widget, m.group("pr"), _pr_url(repo, m.group("pr_num")), base_tags, registry)
        elif m.group("url"):
            _insert_link(widget, m.group("url"), m.group("url"), base_tags, registry)
        pos = m.end()
    if pos < len(text):
        widget.insert(tk.END, text[pos:], base_tags)


def _prepare_lines(source: str) -> tuple[list[str], bool]:
    truncated = False
    if len(source) > _MAX_SOURCE_CHARS:
        source = source[:_MAX_SOURCE_CHARS]
        truncated = True
    lines = source.splitlines()
    if len(lines) > _MAX_LINES:
        lines = lines[:_MAX_LINES]
        truncated = True
    return lines, truncated


def _render_body(widget: tk.Text, source: str, repo: str, registry: list[str]) -> None:
    lines, truncated = _prepare_lines(source)
    prev_blank = True  # suppress a leading blank line
    for raw in lines:
        line = raw.rstrip()
        if not line.strip():
            if not prev_blank:
                widget.insert(tk.END, "\n")
            prev_blank = True
            continue
        prev_blank = False

        heading = _HEADING_RE.match(line)
        bullet = _BULLET_RE.match(line)
        if heading:
            level = min(len(heading.group(1)), 3)
            _emit_inline(widget, heading.group(2).strip(), (f"h{level}",), repo, registry)
            widget.insert(tk.END, "\n")
        elif bullet:
            widget.insert(tk.END, "•  ", ("bullet",))
            _emit_inline(widget, bullet.group(1).strip(), ("bullet",), repo, registry)
            widget.insert(tk.END, "\n")
        else:
            _emit_inline(widget, line, ("body",), repo, registry)
            widget.insert(tk.END, "\n")

    if truncated:
        widget.insert(tk.END, "\n[Release notes truncated]\n", ("body",))


def render_release_notes(widget: tk.Text, source: str, *, fonts: dict[str, tuple], repo: str) -> None:
    """Replace `widget`'s content with `source` rendered as Markdown.

    `widget` is expected to be a normally-disabled (read-only) `tk.Text`;
    this temporarily re-enables it to write, then restores `DISABLED`. Never
    raises -- any parsing failure (there shouldn't be one, since every token
    is optional and the fallback is plain text already, but the release body
    is attacker-influenced in principle) falls back to inserting `source`
    verbatim rather than leaving the dialog broken.
    """
    widget.config(state=tk.NORMAL)

    # Tags from a previous render (per-link click targets) would otherwise
    # accumulate across repeated calls -- see `_insert_link`.
    for tag in getattr(widget, "_md_link_tags", ()):
        try:
            widget.tag_delete(tag)
        except tk.TclError:
            pass
    widget.delete("1.0", tk.END)

    registry: list[str] = []
    try:
        _configure_tags(widget, fonts)
        _render_body(widget, source, repo, registry)
    except Exception:
        for tag in registry:
            try:
                widget.tag_delete(tag)
            except tk.TclError:
                pass
        registry = []
        widget.delete("1.0", tk.END)
        widget.insert("1.0", source)

    widget._md_link_tags = registry  # ty: ignore[unresolved-attribute]
    widget.config(state=tk.DISABLED)
