"""Guards on the sdist -- the archive the in-app updater installs.

``sorter/update/updater.py`` downloads the project's own sdist and unpacks it
over the user's app folder. Nothing declares which files that has to contain:
``pyproject.toml`` configures ``packages = ["src/sorter"]`` only for the
*wheel*, so the sdist falls through to hatchling's default (every VCS-tracked
file, plus hatch-vcs's generated ``src/sorter/_version.py``). That default is
what makes the update path work, and it is exactly the kind of thing a later
``[tool.hatch.build.targets.sdist]`` block would quietly narrow.

``updater.REQUIRED_ENTRY_SETS`` is too thin to catch that: it checks two
files, and an sdist trimmed to just the package would still pass it and then
be applied, leaving a half-updated tree with no error. So assert the real
artifact here instead, the same way test_cliff_config.py asserts the real
git-cliff rather than a description of it.

Skipped when uv isn't installed; CI has it.
"""

from __future__ import annotations

import shutil
import subprocess
import tarfile
from pathlib import Path

import pytest

from sorter.update import updater

ROOT = Path(__file__).resolve().parent.parent.parent

pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(shutil.which("uv") is None, reason="uv not installed"),
]

# What an install has to have on disk to actually run, beyond the package
# itself: the entry point, the dependency bootstrap, both launchers, and the
# metadata bootstrap.py reads to build the venv.
RUNTIME_FILES = (
    "src/sorter/__main__.py",
    # Force-included from src/sorter/_legacy_entry.py (see pyproject.toml).
    # Absent from this tree on purpose; present in every archive, because the
    # launch that *applies* an update runs `python main.py` from a
    # bootstrap.py that predates the src/ layout.
    "main.py",
    "bootstrap.py",
    "start.sh",
    "start.bat",
    "pyproject.toml",
    "uv.lock",
    "src/sorter/__init__.py",
    # Generated by hatch-vcs's build hook rather than tracked in git. Without
    # it an install reports 0.0.0+unknown, which parses as a pre-release, so
    # every launch sees the current release as newer and re-prompts.
    "src/sorter/_version.py",
)


@pytest.fixture(scope="module")
def sdist(tmp_path_factory) -> Path:
    """Build the real sdist once for the module."""
    out = tmp_path_factory.mktemp("dist")
    proc = subprocess.run(
        ["uv", "build", "--sdist", "--out-dir", str(out)],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        pytest.fail(f"uv build --sdist failed:\n{proc.stdout}\n{proc.stderr}")

    tarballs = list(out.glob("*.tar.gz"))
    assert len(tarballs) == 1, f"expected exactly one sdist, got {tarballs}"
    return tarballs[0]


@pytest.fixture(scope="module")
def sdist_names(sdist: Path) -> frozenset[str]:
    """The sdist's members with the single wrapper directory stripped, the
    same way updater._safe_members strips it before staging."""
    with tarfile.open(sdist, mode="r:gz") as tf:
        return frozenset(m.name.split("/", 1)[1] for m in tf.getmembers() if "/" in m.name)


@pytest.mark.parametrize("path", RUNTIME_FILES)
def test_sdist_carries_the_runtime_file(sdist_names: frozenset[str], path: str) -> None:
    assert path in sdist_names, (
        f"{path} is missing from the sdist. The updater unpacks this archive over "
        f"the app folder, so an install updated from it would be missing that file."
    )


def test_sdist_satisfies_the_updaters_own_gate(sdist_names: frozenset[str]) -> None:
    """Whatever else changes, the archive still has to pass stage_update.

    This tree ships the ``src/`` layout, so the sdist it builds will only
    ever satisfy the ``src/sorter/__init__.py`` entry set -- the old flat
    ``REQUIRED_ENTRIES`` set exists purely so an updater built from this tree
    still recognizes an *old-layout* archive it somehow receives (see the
    comment on ``REQUIRED_ENTRY_SETS``). Checking "satisfies at least one
    set" is what actually mirrors ``stage_update``'s own gate.
    """
    satisfied = any(all(e in sdist_names for e in entry_set) for entry_set in updater.REQUIRED_ENTRY_SETS)
    assert satisfied, f"sdist would be rejected by updater.REQUIRED_ENTRY_SETS: {sorted(sdist_names)[:20]}..."


def test_sdist_has_no_symlinks_or_special_entries(sdist: Path) -> None:
    """_safe_members rejects every non-regular entry outright, so the sdist
    growing one would break updates for everyone rather than degrade."""
    with tarfile.open(sdist, mode="r:gz") as tf:
        bad = [m.name for m in tf.getmembers() if not (m.isreg() or m.isdir())]
    assert not bad, f"sdist contains non-regular entries the updater will reject: {bad}"


def test_sdist_filename_matches_what_the_updater_expects(sdist: Path) -> None:
    """The client matches this name exactly; a mismatch degrades it to the
    source archive silently. publish.yml asserts the same thing at release
    time -- this catches it at development time, for the current version."""
    version = sdist.name.removeprefix("ai_case_sorter-").removesuffix(".tar.gz")
    assert sdist.name == updater._expected_asset_name(version)
