"""Case Sorter Open Source Client package."""

# The version bootstrap.py's uv invocations are deliberately built around
# never regenerating (see bootstrap.py's docstring and pyproject.toml's
# [tool.hatch.version]) -- generated fresh only by an actual build (CI, or a
# dev running `uv build`/`hatch build` themselves), where .git is genuinely
# present. sorter.updater compares this against the latest GitHub release
# tag, so getting a real value here matters -- three fallbacks, in order of
# how much they actually tell you:
#
#   1. sorter/_version.py -- generated by hatch-vcs's build hook, gitignored.
#      Present whenever this package was actually built (a release archive
#      the CI publish workflow assembled, or a local `uv build`/`hatch
#      build`). This is the only path that carries the real git-tag version.
#   2. importlib.metadata -- present if this was pip/uv installed from a
#      wheel (e.g. from PyPI, once that's enabled). The wheel's own METADATA
#      already has the version baked in; this doesn't touch git at all.
#   3. A literal fallback. A plain `git clone` + `uv run python main.py`,
#      never built even once, hits this -- there's no real version to give
#      without a build happening somewhere. That's an accepted gap for that
#      one workflow: it's a dev/contributor path, not the release path
#      sorter.updater actually cares about.
try:
    from ._version import __version__  # ty: ignore[unresolved-import]
except ImportError:
    from importlib.metadata import PackageNotFoundError, version

    try:
        __version__ = version("ai-case-sorter")
    except PackageNotFoundError:
        __version__ = "0.0.0+unknown"
